export const FETCH_CHARACTERS_START = "FETCH_CHARACTERS_START";
export const FETCH_CHARACTERS_SUCCESS = "FETCH_CHARACTERS_SUCCESS";
export const FETCH_CHARACTERS_FAIL = "FETCH_CHARACTERS_FAIL";
export const SELECT_CHARACTER = "SELECT_CHARACTER";
export const SEARCH_CHARACTER = "SEARCH_CHARACTER";
export const PAGE_SIZE = "PAGE_SIZE";
export const SET_PAGINATION = "SET_PAGINATION";

export const FETCH_BOOKS_START = "FETCH_BOOKS_START";
export const FETCH_BOOKS_SUCCESS = "FETCH_BOOKS_SUCCESS";
export const FETCH_BOOKS_FAIL = "FETCH_BOOKS_FAIL";
